### PR TITLE
Updated project

### PR DESCRIPTION
**Pull request by colgreen**
This pull requests includes the following changes:

  * Updated nuget refs to latest versions
  * Removed redundant nuget refs, e.g. Newtonsoft.Json.
  * Updated assembly binding redirects.
  * Default hosting URL changed to https (as this is required by the OAuth2 and OIDC protocols).

### CODE REVIEW

**Comment by Shama-K** [comment]
@colgreen, Thank you for your time and effort. Based on your feedback, we have taken up a complete update ourselves and it'd be available soon.

**Comment by colgreen** [comment]
@Shama-K Thanks for looking at this. Yes, I probably went a bit too far updating and removing things :) Hopefully it serves as an example update to work from though.

**Comment by Shama-K** [comment]
@colgreen, it's great, we really appreciate it. 
Latest changes are available in the master branch. Could you please take some time to try the sample and share how it works for you?

**Comment by colgreen** [comment]
Hi @Shama-K, yes this looks much better and up-to-date now. I see there is lots of info in the readme.md now too. 

I tried the app on clean environment and it compiled and ran first time - I used an existing AzureAD account/tenant, so didn't try the new scripts to set that up.

I only have a couple of minor items to report:

1) In README.md, the link to CONTRIBUTING.MD near the bottom is a dead link.
2) The csproj contains a reference to a favicon.ico file, but that file is missing from the git repo, and therefore it appears with a yellow warning triangle in visual studio.

I think I can revoke/close my pull request now.

Thanks again.

**Comment by Shama-K** [comment]
@colgreen, I have noted the points and I'll create a pull request for that. Please go ahead and close this PR.

Thank you.

**Comment by colgreen** [comment]
Closing pull request, as the main branch has been updated to cover all of the issues in this PR.

**Pull request closed without merging**
